# Jekyll Configuration for Anniversary Website
# GitHub Pages Optimized

# Site settings
title: "Our Beautiful Love Story"
description: "A romantic journey through our relationship - Jerry & Puja's Anniversary Website"
url: "https://yourusername.github.io"
baseurl: "/anniversary-website"
author: "Jerry & Puja"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/New_York

# Build settings
sass:
  style: compressed
  sass_dir: _sass

# Collections
collections:
  memories:
    output: true
    permalink: /memories/:name/
  photos:
    output: true
    permalink: /gallery/:name/
  timeline:
    output: true
    permalink: /timeline/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "memories"
    values:
      layout: "memory"
  - scope:
      path: ""
      type: "photos"
    values:
      layout: "photo"
  - scope:
      path: ""
      type: "timeline"
    values:
      layout: "timeline"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links

# GitHub Pages settings
github: [metadata]
repository: yourusername/anniversary-website
github_username: yourusername

# SEO settings
twitter:
  username: yourusername
  card: summary_large_image

social:
  name: "Jerry & Puja"
  links:
    - https://github.com/yourusername

# Site configuration
lang: en_US
locale: en_US

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Our Story"
    url: "/love-story.html"
  - title: "Memories"
    url: "/memories-timeline.html"
  - title: "Photos"
    url: "/photo-gallery.html"
  - title: "Anniversary"
    url: "/anniversary.html"
  - title: "Countdown"
    url: "/countdown.html"
  - title: "Fireworks"
    url: "/fireworks.html"

# Theme settings
theme_settings:
  default_theme: "dark"
  enable_auto_theme: false
  enable_seasonal_themes: true

# Music settings
music_settings:
  enable_cross_page: true
  default_volume: 0.3
  autoplay: false

# Performance settings
performance:
  enable_lazy_loading: true
  enable_image_optimization: true
  enable_caching: true

# Analytics (optional)
google_analytics: # Add your GA4 measurement ID

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md
  - "*.log"
  - package.json
  - package-lock.json
  - webpack.config.js

# Include
include:
  - _pages
  - .htaccess

# Liquid settings
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false
