name: anniversary_flutter
description: Anniversary celebration app with web and mobile support
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
    # UI & Animation
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  lottie: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  confetti: ^0.7.0
  
  # Audio
  audioplayers: ^6.0.0
  just_audio: ^0.9.37
  
  # Storage & State Management
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Platform & Responsive
  flutter_screenutil: ^5.9.0
  device_info_plus: ^10.1.0
  universal_html: ^2.2.4
  
  # Navigation
  go_router: ^13.2.0
    # Network & Performance
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  
  # Web Support
  web: ^0.5.1
    # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
    # Android 13+ Compatibility
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  package_info_plus: ^8.0.2
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  
  # Notification support for Android 13+
  flutter_local_notifications: ^17.0.0
  
  # Enhanced media handling
  photo_manager: ^3.0.0
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/music/
    - assets/animations/
    - assets/fonts/
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
